/* 渐开线外啮合教学模型。长度单位 mm，角度单位 rad。 */
const GearModel=(()=>{
const alpha=Math.PI/9,m=2,z1=20,z2=30;
const inv=a=>Math.tan(a)-a;
function gear(z,ha=1){const r=m*z/2,rb=r*Math.cos(alpha);return{z,r,rb,ra:r+m*ha,rf:r-1.25*m,half:Math.PI/(2*z)}}
function pair(ha=1,delta=0){const g1=gear(z1,ha),g2=gear(z2,ha),a=g1.r+g2.r+delta,aw=Math.acos((g1.rb+g2.rb)/a),rw1=a*z1/(z1+z2),rw2=a-rw1,pb=Math.PI*m*Math.cos(alpha),start=rw2*Math.sin(aw)-Math.sqrt(g2.ra**2-g2.rb**2),end=Math.sqrt(g1.ra**2-g1.rb**2)-rw1*Math.sin(aw);return{g1,g2,a,aw,rw1,rw2,pb,start,end,epsilon:(end-start)/pb}}
function half(g,r){return g.half+inv(alpha)-(r<=g.rb?0:inv(Math.acos(g.rb/r)))}
function contacts(p,phase){const s0=p.start+phase*p.pb,out=[];for(let j=-8;j<=8;j++){const s=s0+j*p.pb;if(s>=p.start-1e-9&&s<p.end-1e-9)out.push({j,s,x:p.rw1+s*Math.sin(p.aw),y:s*Math.cos(p.aw)})}return out}
function rotations(p,phase){const s=p.start+phase*p.pb;return[-half(p.g1,p.rw1)+s/p.g1.rb,Math.PI-half(p.g2,p.rw2)-s/p.g2.rb]}
function limitHeight(){let lo=.1,hi=1;for(let i=0;i<60;i++){const mid=(lo+hi)/2;pair(mid).epsilon<1?lo=mid:hi=mid}return(lo+hi)/2}
return{alpha,m,inv,gear,pair,half,contacts,rotations,limitHeight};})();
if(typeof module!=='undefined')module.exports=GearModel;
if(typeof document!=='undefined')(()=>{
const $=id=>document.getElementById(id),main=$('main'),zoom=$('zoom');let mode='contact',phase=.25,running=false,last=0,lastCount='';
const colors=()=>{let st=getComputedStyle(document.documentElement);return Object.fromEntries(['ink','muted','line','gear1','gear2','outline','a','b','c','d','red','paper'].map(k=>[k,st.getPropertyValue('--'+k).trim()]))};
function setup(canvas,bounds){const w=canvas.clientWidth,h=canvas.clientHeight,dpr=devicePixelRatio||1;canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);const sc=Math.min((w-36)/(bounds[2]-bounds[0]),(h-45)/(bounds[3]-bounds[1])),ox=w/2-sc*(bounds[0]+bounds[2])/2,oy=h/2+sc*(bounds[1]+bounds[3])/2;return{c,w,h,sc,P:(x,y)=>[ox+x*sc,oy-y*sc]}}
function line(v,a,b,col,width=1,dash=[]){const c=v.c;c.beginPath();c.setLineDash(dash);c.strokeStyle=col;c.lineWidth=width;c.moveTo(...v.P(...a));c.lineTo(...v.P(...b));c.stroke();c.setLineDash([])}
function circle(v,x,y,r,col,dash=[]){const c=v.c;c.beginPath();c.setLineDash(dash);c.strokeStyle=col;c.lineWidth=1;c.arc(...v.P(x,y),r*v.sc,0,Math.PI*2);c.stroke();c.setLineDash([])}
function label(v,s,x,y,col,dx=0,dy=0){const c=v.c,p=v.P(x,y);c.font='13px system-ui';c.fillStyle=col;c.textAlign='left';const width=c.measureText(s).width;c.fillText(s,Math.max(4,Math.min(v.w-width-4,p[0]+dx)),Math.max(15,Math.min(v.h-4,p[1]+dy)))}
function dot(v,x,y,col,r=4){v.c.beginPath();v.c.fillStyle=col;v.c.arc(...v.P(x,y),r,0,Math.PI*2);v.c.fill()}
function drawGear(v,g,cx,theta,fill,activeMap,C){const c=v.c,sc=v.sc;function pt(r,a){return v.P(cx+r*Math.cos(a),r*Math.sin(a))}c.beginPath();c.arc(...v.P(cx,0),g.rf*sc,0,Math.PI*2);c.fillStyle=fill;c.fill();c.strokeStyle=C.outline;c.lineWidth=1;c.stroke();for(let i=0;i<g.z;i++){const angle=theta+i*2*Math.PI/g.z,points=[],r0=Math.max(g.rb,g.rf),hb=GearModel.half(g,r0);points.push(pt(g.rf,angle-hb));for(let n=0;n<=24;n++){const r=r0+(g.ra-r0)*n/24;points.push(pt(r,angle-GearModel.half(g,r)))}const ht=GearModel.half(g,g.ra);for(let n=1;n<=8;n++)points.push(pt(g.ra,angle-ht+2*ht*n/8));for(let n=24;n>=0;n--){const r=r0+(g.ra-r0)*n/24;points.push(pt(r,angle+GearModel.half(g,r)))}points.push(pt(g.rf,angle+hb));c.beginPath();points.forEach((p,j)=>j?c.lineTo(...p):c.moveTo(...p));c.closePath();c.fillStyle=activeMap.get(i)||fill;c.fill();c.beginPath();points.forEach((p,j)=>j?c.lineTo(...p):c.moveTo(...p));c.strokeStyle=C.outline;c.lineWidth=1;c.stroke()}circle(v,cx,0,3,C.outline);dot(v,cx,0,C.outline,2)}
function state(){let ha=$('preset').value==='short'?.35:$('preset').value==='limit'?GearModel.limitHeight():1;return GearModel.pair(mode==='center'?1:ha,mode==='center'?Number($('delta').value):0)}
function gears(canvas,p,isZoom=false){const C=colors(),v=setup(canvas,isZoom?[p.rw1-9,-12,p.rw1+9,12]:[-p.g1.ra-2,-p.g2.ra-3,p.a+p.g2.ra+2,p.g2.ra+3]),cs=GearModel.contacts(p,phase),theta=GearModel.rotations(p,phase),a1=new Map(),a2=new Map(),palette=[C.a,C.b,C.c,C.d];cs.forEach(q=>{let col=palette[((q.j%4)+4)%4];a1.set(((q.j%p.g1.z)+p.g1.z)%p.g1.z,col);a2.set(((-q.j%p.g2.z)+p.g2.z)%p.g2.z,col)});drawGear(v,p.g1,0,theta[0],C.gear1,a1,C);drawGear(v,p.g2,p.a,theta[1],C.gear2,a2,C);
if(mode==='circles'){[[p.g1,0],[p.g2,p.a]].forEach(([g,x])=>{circle(v,x,0,g.ra,C.a);circle(v,x,0,g.r,C.d,[7,4]);circle(v,x,0,g.rb,C.b,[2,3]);circle(v,x,0,g.rf,C.c,[8,3,2,3])})}else if(mode==='center'){[[p.g1,0,p.rw1],[p.g2,p.a,p.rw2]].forEach(([g,x,rw])=>{circle(v,x,0,g.r,C.d,[7,4]);circle(v,x,0,g.rb,C.b,[2,3]);circle(v,x,0,rw,C.a)})}else{circle(v,0,0,p.rw1,C.line,[5,4]);circle(v,p.a,0,p.rw2,C.line,[5,4])}
const point=s=>[p.rw1+s*Math.sin(p.aw),s*Math.cos(p.aw)];line(v,point(p.start-2),point(p.end+2),C.muted,1,[4,3]);line(v,point(p.start),point(p.end),C.red,2);dot(v,p.rw1,0,C.ink,3);label(v,'P',p.rw1,0,C.ink,5,16);if(isZoom){let q=point(p.start);label(v,'B₂ 进入',...q,C.ink,-76,16);q=point(p.end);label(v,'B₁ 退出',...q,C.ink,8,-8)}cs.forEach(q=>{dot(v,q.x,q.y,C.paper,6);dot(v,q.x,q.y,palette[((q.j%4)+4)%4],4)});if(!isZoom){label(v,'O₁',0,0,C.ink,6,18);label(v,'O₂',p.a,0,C.ink,6,18)}}
function involute(){const C=colors(),g=GearModel.gear(20),v=setup(main,[-26,-25,34,30]),t=.02+phase/3*.8,rb=g.rb,pt=a=>[rb*(Math.cos(a)+a*Math.sin(a)),rb*(Math.sin(a)-a*Math.cos(a))],B=[rb*Math.cos(t),rb*Math.sin(t)],P=pt(t),phi=Math.atan2(P[1],P[0]);circle(v,0,0,rb,C.b);circle(v,0,0,g.r,C.d,[6,4]);circle(v,0,0,g.ra,C.a,[2,4]);line(v,[0,0],B,C.b);line(v,[0,0],P,C.muted);line(v,B,P,C.c,3);const c=v.c;c.beginPath();for(let i=0;i<=150;i++){const q=v.P(...pt(t*i/150));i?c.lineTo(...q):c.moveTo(...q)}c.strokeStyle=C.a;c.lineWidth=3;c.stroke();const tv=[-Math.sin(phi),Math.cos(phi)];line(v,[P[0]-7*tv[0],P[1]-7*tv[1]],[P[0]+7*tv[0],P[1]+7*tv[1]],C.d,1,[4,3]);dot(v,...B,C.b);dot(v,...P,C.a);label(v,'B 切点',...B,C.ink,-35,-15);label(v,'P 线头',...P,C.ink,8,18);label(v,'O',0,0,C.ink,-15,16);const ap=Math.atan(t)*180/Math.PI;label(v,'此处压力角 '+ap.toFixed(1)+'°',-24,-22,C.ink);$('phase-label').textContent='OP = '+Math.hypot(...P).toFixed(2)+' mm；分度圆半径 = 20 mm';}
const lessons={contact:'<h2>先盯住同色的两颗齿</h2><p>同一颜色表示正在接触的一对轮齿。两种颜色同时出现，说明前一对尚未退出，后一对已开始接触。放大图中，接触点从 B₂ 移到 B₁；节点 P 固定，接触点会经过它。</p><p class="formula">重合度 εα＝B₁B₂ / pᵦ＝一对齿的接触时长 / 相邻齿对开始接触的时间间隔</p><p>默认方案中会交替出现一对、两对齿接触。切换“缩短齿高”，齿顶变短使实际啮合线缩短，观察接触数变为 0 的空档。临界方案 ε＝1 只在理想几何条件下刚好接班。</p>',circles:'<h2>这四个圆各自负责什么？</h2><table><tr><th>圆</th><th>作用</th></tr><tr><td>分度圆（虚线）</td><td>由 m、z 确定的尺寸基准，d＝mz</td></tr><tr><td>基圆（点线）</td><td>生成渐开线，db＝d cosα</td></tr><tr><td>齿顶圆（实线）</td><td>通过齿尖，标准正常齿 da＝m(z＋2)</td></tr><tr><td>齿根圆（点划线）</td><td>通过槽底，标准正常齿 df＝m(z－2.5)</td></tr></table><p>基圆不是齿根圆。基圆与齿根圆的内外顺序取决于齿数，不能只记图中的顺序。分度圆也不是齿高的严格中线。</p>',involute:'<h2>BP 是细线，OP 是半径连线</h2><p>绷紧的 BP 始终与基圆相切，P 的轨迹形成一个齿侧的渐开线。虚线分度圆先由 m、z 确定；P 穿过它时，OP 恰好等于分度圆半径。展开并不需要在那里停止。</p><p>经过 P 的短虚线是该处同心圆的切线。它与 BP 的夹角为该点压力角。越往外，压力角越大；到分度圆上才是此例的 20°。</p><button id="at-pitch">把 P 放在分度圆上</button>',center:'<h2>分度圆不随安装改变，节圆会改变</h2><p>拖动中心距：两个齿轮本身的分度圆与基圆保持原大小；橙色节圆重新分配半径，在节点 P 相切。工作压力角增大，实际啮合线缩短，重合度下降。</p><p class="formula">cosαw＝(rb₁＋rb₂)/a；rw₁＋rw₂＝a；rw₂/rw₁＝z₂/z₁</p><p>标准中心距时，本例节圆与分度圆重合。节点 P 是节圆切点，也是固定啮合线与连心线的交点。转动时接触点经过 P，但不会始终停在 P。</p>'};
function render(){const p=state();$('ratio').textContent=mode==='involute'?'m＝2 mm，z＝20，α＝20°':'εα＝'+p.epsilon.toFixed(3);const cs=GearModel.contacts(p,phase),s=mode==='involute'?'基圆固定，细线展开':'当前 '+cs.length+' 对接触'+(!cs.length?' · 空档':'');if(s!==lastCount){$('count').textContent=s;lastCount=s}$('phase-label').textContent=mode==='center'?'a＝'+p.a.toFixed(1)+' mm，αw＝'+(p.aw*180/Math.PI).toFixed(2)+'°':'L＝'+(p.end-p.start).toFixed(2)+' mm，pᵦ＝'+p.pb.toFixed(2)+' mm';$('delta-label').textContent=Number($('delta').value).toFixed(1)+' mm';if(mode==='involute')involute();else{gears(main,p);gears(zoom,p,true)}}
function changeMode(next){stop();mode=next;$('lesson').innerHTML=lessons[mode];$('center-control').hidden=mode!=='center';$('preset').parentElement.hidden=mode==='involute'||mode==='center';$('zoom-wrap').hidden=mode==='involute';document.querySelector('.views').classList.toggle('single',mode==='involute');$('main-title').textContent=mode==='involute'?'渐开线生成 · 对应一个轮齿的侧面':'整对齿轮 · 左轮逆时针，右轮顺时针';document.querySelectorAll('nav button').forEach(b=>b.setAttribute('aria-pressed',b.dataset.mode===mode));const C=colors(),legend=mode==='circles'?[['齿顶圆',C.a],['分度圆',C.d],['基圆',C.b],['齿根圆',C.c]]:mode==='center'?[['分度圆',C.d],['基圆',C.b],['节圆',C.a]]:mode==='involute'?[['基圆',C.b],['分度圆',C.d],['齿顶圆 / 渐开线',C.a],['绷紧的细线',C.c]]:[['高亮齿对：同时参与接触',C.a],['实际啮合线 B₂B₁',C.red]];$('legend').innerHTML=legend.map(([s,c])=>'<span><i class="swatch" style="background:'+c+'"></i>'+s+'</span>').join('');if($('at-pitch'))$('at-pitch').onclick=()=>{stop();phase=(Math.tan(GearModel.alpha)-.02)/.8*3;$('phase').value=phase;render()};render()}
function stop(){running=false;$('play').textContent='播放'}function tick(now){if(!running)return;if(last)phase=Math.min(3,phase+(now-last)/1000*Number($('speed').value));last=now;$('phase').value=phase;render();if(phase>=3){stop();return}requestAnimationFrame(tick)}$('play').onclick=()=>{if(running){stop();return}if(phase>=3)phase=0;running=true;last=0;$('play').textContent='暂停';requestAnimationFrame(tick)};$('reset').onclick=()=>{stop();phase=0;$('phase').value=0;render()};$('phase').oninput=()=>{stop();phase=Number($('phase').value);render()};$('delta').oninput=render;$('preset').onchange=render;document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>changeMode(b.dataset.mode));new ResizeObserver(render).observe(main);window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>changeMode(mode));changeMode('contact');
})();
